name: type_is-ci

on: [push, pull_request]

jobs:
  type_is:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]

    steps:
      - uses: actions/checkout@v2
      - uses: denolib/setup-deno@master
        with:
          deno-version: 1.13.0

      - run: deno --version
      - run: deno fmt --check
      - run: deno test -A
